Überarbeitung BW Arsenal
TacticalBaconDevs/TBMod pull request #521
Opened 2020-09-10 15:28 UTC by E-for-Eron

Standardlayouts werden noch angepasst.
Ausrüstung/Arsenal fertig.

2020-09-10 16:52 UTC, Er1807 approved these changes
vlt. kann man direkt die Müllvisiere aus dem US Arsenal entfernen

2020-09-11 21:43 UTC, E-for-Eron commented
Fertig für Merge.

2020-09-12 12:38 UTC, shukari requested changes
Wir müssen uns Fragen, ob wir Arsenale machen, die alleine funktionieren oder ob wir sagen RHS ist sowieso immer mit dabei...

2020-09-12 12:38 UTC, shukari commented on addons/arsenal/arsenale/fnc_arsenalBW.sqf
> +    "NVGoggles",
Haben die das ACE NightVision Feature

2020-09-12 12:38 UTC, shukari commented on addons/arsenal/arsenale/fnc_arsenalBW.sqf
> +    "rhs_mag_mk3a2",
RHS ist in BW nicht erlaubt, da es ggf nicht da ist (weiß, das ist selten)

2020-09-12 12:38 UTC, shukari commented on addons/arsenal/arsenale/fnc_arsenalBW.sqf
> -    case "dmr":
soll die DMR Rolle raus? dann muss hier aber was leeres zurück
`case "dmr": {[]};` (wie in USA) zudem muss die Rolle geblacklistet werden, mache ich dann wenn es so gewünscht ist

2020-09-12 12:38 UTC, shukari commented on addons/nachschub/configs/CfgVehicles_BW.hpp
> +        MACRO_ADDMAGAZINE(rhs_mag_mk3a2,10);        // Splitternade
RHS in BW ggf nicht verfügbar da Mod nicht geladen

2020-09-12 12:38 UTC, shukari commented on addons/nachschub/configs/CfgVehicles_UK.hpp
> +        MACRO_ADDMAGAZINE(rhs_mag_mk3a2,20);    // Offensivenade
Hier ist wieder die Frage ob RHS bei UK

2020-09-12 12:38 UTC, shukari commented on addons/nachschub/configs/CfgVehicles_USA.hpp
> +        MACRO_ADDMAGAZINE(rhs_mag_mk3a2,20);    // Offensivenade
Wird die m67 zu wenig verwendet?

2020-09-12 12:38 UTC, shukari commented on addons/rhs/CfgAmmo.hpp
> -        caliber = 5.04; // 3.6
Wars zu stark?

2020-09-12 12:38 UTC, shukari commented on addons/arsenal/arsenale/fnc_arsenalBW.sqf
> +            "rhs_weap_M320",
RHS Waffe in BW

2020-09-12 13:24 UTC, merged