99/100%
TacticalBaconDevs/TBMod pull request #605
Opened 2021-02-09 13:37 UTC by E-for-Eron

EditorPreviews und sonstige Bilder von TB Fahrzeugen entfernt, die nicht mehr benötigt werden (Hunter ist durch RHS M-ATV Reihe ersetzt, Striderversion mit HMG oben entfernt etc). Dafür kommt das FV510 Warrior hinzu - in Komplettüberarbeitung [ich möchte meine Lebenszeit zurück! ].
TB Skin Fahrzeuge sind der Übersicht halber nach TB Skin Vehicle übertragen worden.
Alle TB Fahrzeuge werden nun mit SLAT Käfigen etc gespawnt (gilt auch für Fahrzeuge, die per Modul nachgeführt werden) und können jederzeit ohne Probleme per direkter Auswahl oder per Garage jeweils in Camouflage und Ausrüstung angepasst werden. Displaynames wurden zwecks Übersicht angepasst, um in Modulen erkennen zu können, welches Fahrzeug gespawnt wird. [Lebenszeit!]

@shukari **Es gibt noch ein Problem, für das ich keine Lösung finden konnte**: die originale AAF Warrior Version hat keinen funktionierenden Turm mehr. Liegt an der Vererbung der class Mainturret vom neuen TB_Vehicles_Wald_Warrior. Ab Zeile 656, Skins/Cfg Vehicles. Das neue Modell funktioniert einwandfrei mit allen neuen Waffen.
Was habe ich an der Vererbung falsch gemacht?

2021-02-10 14:05 UTC, E-for-Eron commented
Es folgt heute noch ein Commit zu Hitpoints, da einzelne Waffensysteme die Wanne direkt zum Cook-Off Effekt zwingen.

2021-02-10 14:45 UTC, shukari requested changes
Richtig guter PR, müssen nur über ein paar Sachen reden was du da genau willst. An einigen Stellen wird zuviel gemacht, an anderen muss ich erst rumexperiementieren...

2021-02-10 14:45 UTC, shukari commented on addons/config/configs/CfgAmmo.hpp
> +        class CamShakeExplode
Was ist hier anders als bei **_B_40mm_GPR_Tracer_Red_**

2021-02-10 14:45 UTC, shukari commented on addons/config/configs/CfgAmmo.hpp
> +    };
Was ist hier anders?

2021-02-10 14:45 UTC, shukari commented on addons/config/configs/CfgAmmo.hpp
> +        class CamShakeExplode
Da reden wir im TS3 einach nochmal warum hier die ganzen Unterklassen nochmal definiert werden.

2021-02-10 14:45 UTC, shukari commented on addons/config/configs/CfgVehicles.hpp
> +        class AnimationSources : AnimationSources
Da müssen wir überall mal drüber reden.
Generell -> https://community.bistudio.com/wiki/Class_Inheritance

2021-02-10 14:45 UTC, shukari commented on addons/config/configs/CfgWeapons.hpp
> +            class player;
puh... weiß nicht ob das geht... woher soll danach bekannt sein ob du die **_class player_** aus AP oder HE meinst 😕

2021-02-10 14:45 UTC, shukari commented on addons/skins/configs/CfgVehicles.hpp
>          };
Wird doch alles per Skript gelöscht. Müsste man ggf per config-Wert ausnahmen machen hmmm

2021-02-10 18:39 UTC, E-for-Eron commented on addons/skins/configs/CfgVehicles.hpp
>          };
Soll drin bleiben, weil das Script deaktiviert werden kann und ich nicht jede Mission neu das zusammenstellen möchte, bzw wenn es nicht benötigt wird, einfach per Script gelöscht wird.

2021-02-10 23:04 UTC, E-for-Eron commented on addons/config/configs/CfgAmmo.hpp
> +        class CamShakeExplode
Siehe "Anzeigen der Änderungen + Armor Upgrade" Commit.
Personen nahe der Einschläge hatten zu starkes Bildschirmwackeln - wäre damit nicht urban mehr nutzbar.

2021-02-10 23:04 UTC, E-for-Eron commented on addons/config/configs/CfgAmmo.hpp
> +    };
Siehe "Anzeigen der Änderungen + Armor Upgrade" Commit.
Personen nahe der Einschläge hatten zu starkes Bildschirmwackeln - wäre damit nicht urban mehr nutzbar.

2021-02-10 23:07 UTC, E-for-Eron commented on addons/config/configs/CfgWeapons.hpp
> +            class player;
Das habe ich mich beim Original von Bohemia auch gefragt. Ich kann doch nicht die Class Names einfach ändern, ohne die Vererbung zu verlieren, sodass dann die Unterklasse neu definiert müsste, oder?

2021-02-21 17:07 UTC, shukari approved these changes
Werde es demnächst umstrukturieren, sollte aber nicht den PR verzögern, deswegen erstmal so durch.

2021-02-21 17:08 UTC, merged